"use client";

import "./globals.css";
import Footer from "./(components)/footer/footer";
import Header from "./(components)/header/header";
import { BsArrowUp } from "react-icons/bs";
import { createContext, useEffect, useState } from "react";

const metadata = {
  title: "Digi Store",
  description: "Generated by create next app",
};

export const ProductsContext = createContext(null);

export default function RootLayout({ children }) {
  const [products, setProducts] = useState([]);
  const [visible, setVisible] = useState(false);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  useEffect(() => {
    fetch("/data/productsData.json")
      .then((res) => res.json())
      .then((data) => setProducts(data))
      .catch((err) => console.error("Error fetching data:", err));
    const toggleVisibility = () => {
      setVisible(window.scrollY > 300);
    };
    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"
          integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={`antialiased`}>
        <Header />
        <button
          className={`fixed right-10 bottom-10 w-14 h-14 z-20 rounded-full flex items-center justify-center bg-slate-200 shadow-lg ${visible ? 'opacity-100' : 'opacity-0'}`}
          onClick={scrollToTop}
        >
          <BsArrowUp />
        </button>
        <ProductsContext.Provider value={products}>
          {children}
        </ProductsContext.Provider>
        <Footer />
      </body>
    </html>
  );
}
